# Generated by Django 5.0.3 on 2024-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='EnCategory',
        ),
        migrations.AlterField(
            model_name='fidocument',
            name='categories',
            field=models.ManyToManyField(to='materials.ficategory'),
        ),
    ]
