# Generated by Django 5.0.3 on 2024-05-13 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enhomepost_fihomepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enhomepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
