# Generated by Django 5.0.3 on 2024-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_company_address_user_company_email_user_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_email',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
